AXHttp: ax_http_server_socket.h File Reference
ax_http_server_socket.h File Reference
The AXHttpServerSocket and its associated functions.
Typedefs
typedef void(* SocketRequestCallback) (const gchar *path, const gchar *method, const gchar *query, GHashTable *parameters, gint reply_fd, gpointer user_data)
This is the prototype of the callback function called whenever an matching http request is received.
typedef struct _AXHttpServerSocket AXHttpServerSocket
The AXHttpServerSocket is an opaque data type.
Functions
AXHttpServerSocket * ax_http_server_socket_new (const gchar *name, SocketRequestCallback request_callback, gpointer user_data)
Creates a new AXHttpServerSocket.
void ax_http_server_socket_free (AXHttpServerSocket *socket)
Destroys the AXHttpServerSocket. Any pending callbacks associated with theAXHttpServerSocket will be cancelled.
Detailed Description
The AXHttpServerSocket and its associated functions.
Typedef Documentation
SocketRequestCallback
typedef void(* SocketRequestCallback) (const gchar *path, const gchar *method, const gchar *query, GHashTable *parameters, gint reply_fd, gpointer user_data)
This is the prototype of the callback function called whenever an matching http request is received.
Parameters
path The path on which the request was made.
method The http method used for the request.
query The full query string.
parameters A GHashTable with parameters.
reply_fd The file descriptor to be used for the reply.
user_data Optional user data.
Function Documentation
ax_http_server_socket_new()
AXHttpServerSocket* ax_http_server_socket_new (const gchar * name, SocketRequestCallback request_callback, gpointer user_data)
Creates a new AXHttpServerSocket.
Returns
a newly allocated AXHttpServerSocket.
References ax_http_server_socket_free().
Referenced by ax_http_handler_new().
ax_http_server_socket_free()
void ax_http_server_socket_free (AXHttpServerSocket * socket)
Destroys the AXHttpServerSocket. Any pending callbacks associated with theAXHttpServerSocket will be cancelled.
Parameters
socket a AXHttpServerSocket.
Referenced by ax_http_handler_free(), and ax_http_server_socket_new().