# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AXIS ACAP 4 SDK Documentation
description: > # this means to ignore newlines until "baseurl:"
  AXIS ACAP 4 SDK Documentation contains two types
  of SDKs; A Native SDK and a Computer Vision SDK
baseurl: "" # the subpath of your site, e.g. /blog
copyright_name: Axis Communications AB
url: "www.axis.com" # the base hostname & protocol for your site
github_username:  AxisCommunications

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

exclude:
  - README.md
  - Dockerfile
  - vendor
