# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ------------------------------------------------------------------------------
# Site settings

title: ACAP documentation
description: >
  ACAP documentation is the point of reference for ACAP application development.

url: https://axiscommunications.github.io # The base hostname & protocol
baseurl: /acap-documentation # The subpath of your site

github_username:  AxisCommunications
copyright_name: Axis Communications AB
copyright_footer: "&copy;<script>new Date().getFullYear()>document.write(new Date().getFullYear());</script> Axis Communications AB. All rights reserved. AXIS COMMUNICATIONS, AXIS, ARTPEC and VAPIX are registered trademarks of Axis AB in various jurisdictions, and you are not granted any license to use them. All other trademarks are the property of their respective owners."

logo: /assets/logos/axis-logo.png

# ------------------------------------------------------------------------------
# Build settings

remote_theme: just-the-docs/just-the-docs

exclude:
  - build-multistage
  - CODE_OF_CONDUCT.md
  - CODEOWNERS
  - CONTRIBUTING.md
  - Dockerfile*
  - Gemfile*
  - LICENSE
  - README.md
  - renovate.json
  - TROUBLESHOOTING.md

# It's better to use kramdown than the GitHub Markdown renderer which works
# poorly with this theme
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# ------------------------------------------------------------------------------
# Plugins

#  GitHub Pages does not use bundle to install plugins, which means that only
#  the ones listed here will be installed on GitHub Pages.
#
#  GitHub Pages supports a limited set of plugins, see which ones here:
#  https://pages.github.com/versions

#  jekyll-remote-theme: To load remote theme
#  jekyll-sitemap: Generates a "sitemap.xml" for search engines.
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# ------------------------------------------------------------------------------
# Theme settings

# SCSS overrides
color_scheme: axis

# Launch GitHub link on top in new web browser tab
aux_links_new_tab: true
aux_links:
  "ACAP documentation on GitHub":
    - //github.com/AxisCommunications/acap-documentation

search_enabled: true
heading_anchors: true

# Google Analytics Tracking
ga_tracking: UA-266925-56

# Back to top link
back_to_top: true
back_to_top_text: Back to top
