# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

##### Site settings #####
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and
# so on. You can create any custom variable you would like, and they will be
# accessible in the templates via {{ site.myvariable }}.

title: AXIS ACAP 4 SDK Documentation
description: > # This means to ignore newlines until "baseurl:"
  AXIS ACAP 4 SDK Documentation contains two types
  of SDKs; A Native SDK and a Computer Vision SDK
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://AxisCommunications.github.io" # The base hostname & protocol for
                                            # your site, e.g. http://example.com
github_username:  AxisCommunications
copyright_name: Axis Communications AB
copyright_footer: "&copy;<script>new Date().getFullYear()>document.write(new Date().getFullYear());</script> Axis Communications AB. AXIS COMMUNICATIONS, AXIS, ARTPEC and VAPIX are registered trademarks of Axis AB in various jurisdictions. All other trademarks are the property of their respective owners."
#logo: "/assets/logos/logo_axis_color_rgb.jpg"
logo: "/assets/logos/axis-logo.png"
#logo: "/assets/logos/logo.svg"

exclude: ["Dockerfile",  "Dockerfiles/", "Gemfile", "Gemfile.lock",
"LICENSE.txt", "README.md", "vendor"]


##### General settings #####

# Markdown and highlighting settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge


##### Theme settings #####

theme: "just-the-docs"

# SCSS overrides
color_scheme: axis

# Launch Github link on top in new web browser tab
aux_links_new_tab: true
aux_links:
  "ACAP 4 SDK documentation on GitHub":
    - "//github.com/AxisCommunications/acap-documentation"

search_enabled: true
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
