AXIS_USABLE_LIBS = UCLIBC GLIBC
include $(AXIS_TOP_DIR)/tools/build/rules/base.mak
include $(AXIS_TOP_DIR)/tools/build/rules/recurse.mak

SUBDIRS = key_value_set_example1 \
	  key_value_set_example2 \
	  property_state_declaration_example \
	  property_state_declaration_from_template_example \
	  send_event_example \
	  stateless_declaration_example \
	  stateless_declaration_from_template_example \
	  subscription_example \
	  element_item_example
