name: Build documentation from Dockerfiles
on:
  push:
     paths:
      - '**'
      - '.github/workflows/build-dockerfiles.yml'
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!LICENSE.*'
      - '!CODEOWNERS'
      - '!CODE_OF_CONDUCT.md'
jobs:
  build-docs-in-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test pages
      run: |
        t0=testimage:0

        printf "### Build main Dockerfile\n"
        docker build . --no-cache -t $t0

        printf "### Build multi stage Dockerfiles\n"
        ./build-multistage full
